export const ADD_USER_NAME = 'ADD_USER_NAME';
export const SET_COUNT_CLICK = 'SET_COUNT_CLICK';
export const SET_COUNT_SECONDS = 'SET_COUNT_SECONDS';
export const SET_COUNT_LEFT_SECONDS = 'SET_COUNT_LEFT_SECONDS';
export const START_TIMER = 'START_TIMER';
export const RESET_TIMER = 'RESET_TIMER';
export const UPDATE_GAME_RESULTS = 'UPDATE_GAME_RESULTS'